import os
import sys
import platform

OS_NAME = platform.system();
LIB_DIR=os.environ['LIB_DIR'];
BIN_DIR=os.environ['BIN_DIR'];

env=DefaultEnvironment().Clone()
SOURCES=Glob('spine-cpp/spine-cpp/src/spine/*.cpp') + ['spine-cpp/spine-cpp-lite/spine-cpp-lite.cpp']

env.Library(os.path.join(LIB_DIR, 'spine'), SOURCES);

